[package]
name = "typub-markdown"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Markdown rendering utilities for typub"

[dependencies]
anyhow.workspace = true
comrak.workspace = true
enumset.workspace = true
tylax.workspace = true
typub-core.workspace = true
typub-html.workspace = true
typub-ir.workspace = true
typub-storage.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
