[package]
name = "typub-passes"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Semantic IR passes for typub"

[dependencies]
anyhow.workspace = true
resvg.workspace = true
scraper.workspace = true
serde_json.workspace = true
tiny-skia.workspace = true
typub-core.workspace = true
typub-html.workspace = true
typub-ir.workspace = true
typub-storage.workspace = true
usvg.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
