[package]
name = "typub-tui"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Terminal UI for typub"

[features]
default = ["s3"]
s3 = ["typub-engine/s3", "typub-storage/s3"]

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
html2text.workspace = true
open.workspace = true
ratatui.workspace = true
typub-config.workspace = true
typub-core.workspace = true
typub-engine.workspace = true
typub-storage.workspace = true
typub-ui.workspace = true

[lints]
workspace = true
