[package]
name = "typub-ir"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Semantic IR types for typub"
publish = false

[dependencies]
relative-path.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
