[package]
name = "typub-log"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Logging foundation for typub based on tracing"

[dependencies]
owo-colors.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
